server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud: #利用网关路由映射，实现反向代理
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由（默认是开启的）
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          #注释掉原始的Uri,以注册中心上微服务名为路径创建动态路由进行转发，从而实现动态路由的功能,实现了负载均衡
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - Method=GET
            - Before=2023-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- After=2022-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Between=2022-03-08T10:59:34.102+08:00[Asia/Shanghai],2023-03-08T10:59:34.102+08:00[Asia/Shanghai]
            - Cookie=username,atguigu    #并且Cookie是username=atguigu才能访问
            - Query=user,wuyang,\d+ #要有参数名称并且是正整数才能路由
            #- Host=http://localhost:** #主机名必须是这个才能访问
            #- Header=X-Request-Id,\d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
